# 
# 
# 
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript?view=azure-devops 

pool:
  vmImage: 'ubuntu-16.04' # examples of other options: 'macOS-10.13', 'vs2017-win2016'
strategy:
  matrix:
    node_9_x:
      node_version: 9.x

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: $(node_version)



